name: python3.5-oddbloke
version: '3.5' # just for humans, typically '1.2+git' or '1.3.2'
summary: Python 3.5
description: |
  Just Python 3.5

grade: devel
confinement: classic

parts:
  python35:
    plugin: nil
    stage-packages:
      - python3.5
